image: python:3.12

stages:
  - lint
  - type_check
  - test
  - performance

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python -V
  - pip install --upgrade pip
  - pip install black ruff mypy pytest pytest-cov

# 코드 포맷팅 검사 (black)
format:
  stage: lint
  script:
    - pip install black
    - black --check --diff .

# 코드 린팅 (ruff)
lint:
  stage: lint
  script:
    - pip install ruff
    - ruff check .

# 타입 체크 (mypy)
type_check:
  stage: type_check
  script:
    - pip install mypy
    - pip install types-psutil==7.0.0.20250516
    - mypy --strict .

# 테스트 실행 (pytest)
test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pip install psutil
    - pytest --cov=. --cov-report=term --cov-report=xml
  coverage: '/TOTAL.*\s+(\d+%)/'
  artifacts:
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# 커버리지 검증
coverage_check:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pip install psutil
    - pytest --cov=. --cov-report=term
    - coverage_result=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(float(root.attrib['line-rate']) * 100)")
    - echo "Coverage is $coverage_result%"
    - |
      if (( $(echo "$coverage_result < 80" | bc -l) )); then
        echo "Coverage is below 80%"
        exit 1
      else
        echo "Coverage is at or above 80%"
      fi
  needs:
    - test

# 성능 검증
performance:
  stage: performance
  script:
    - pip install pytest pytest-benchmark psutil
    - pytest -m perf --benchmark-only || true
    - python -c "import psutil; print('Memory:', psutil.Process().memory_info().rss / 1024 / 1024, 'MB')"
    - echo 'Performance checks completed'
  allow_failure: false
  needs:
    - test
