services:
  # 프론트엔드 서비스 (메인)
  - type: web
    name: chickenmaster
    runtime: node
    plan: free
    region: singapore
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://api.chickenmaster.onrender.com
      - key: PORT
        value: "10000"
      - key: NODE_VERSION
        value: "20.11.1"
    autoDeploy: true

  # 백엔드 API 서비스
  - type: web
    name: chickenmaster-api
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      # AWS S3 설정 (이미지/에셋 저장용)
      - key: AWS_ACCESS_KEY_ID
        sync: false  # Render 대시보드에서 직접 입력
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        value: ap-northeast-2
    autoDeploy: true
    healthCheckPath: /health

  # 정적 파일 서비스
  - type: web
    name: chickenmaster-static
    runtime: static
    buildCommand: echo "Static files service"
    staticPublishPath: ./data/events_bank/images
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 