name: CI

on:
  push:
    branches: [ main, dev, feature/*, fix/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Lint with ruff
        run: ruff check .
      - name: Check formatting with black
        run: black --check --diff .

  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install types-psutil==7.0.0.20250516
      - name: Type check with mypy
        run: mypy --strict .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov psutil
      - name: Test with pytest
        run: pytest --cov=. --cov-report=term --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
      - name: Check coverage threshold
        run: |
          coverage_result=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(float(root.attrib['line-rate']) * 100)")
          echo "Coverage is $coverage_result%"
          if (( $(echo "$coverage_result < 80" | bc -l) )); then
            echo "Coverage is below 80%"
            exit 1
          else
            echo "Coverage is at or above 80%"
          fi

  performance:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-benchmark psutil
      - name: Run performance tests
        run: |
          pytest -m perf --benchmark-only || true
          python -c "import psutil; print('Memory:', psutil.Process().memory_info().rss / 1024 / 1024, 'MB')"
          echo 'Performance checks completed'
